#DEV OP
## DATABASES
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tajyire_local_db
    username: postgres
    password: 123
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
  sendgrid:
    api-key: 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
  #Multipart File Size
  servlet:
    multipart:
      enabled: true
      max-file-size: "5MB"
  profiles:
    active: dev
cloudinary:
  cloud_name: rutaks
  api_key: 185334393241981
  api_secret: MSUzLG_ixg_VM0_lf0ASlkLGN6k

jwt.secret: secret
