## DATABASES
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/tajyire_dev_db
  username: postgres
  password: 123
 jpa:
  hibernate.ddl-auto: update
  show-sql: true
  properties.hibernate.format_sql: true

jwt.secret: tajyire_secret